Repository Team-Frolog/Frolog-frontend, pull requests merged in 2024-03, with the labels that each got.

#4 [Style/#3]: 레이아웃 잡기
  .eslintrc.json
  src/App.tsx
  src/components/layout/MainLayout.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/styles/GlobalStyles.ts
Labels: style, 지민 😎

#7 [Feat/#2]: 공통 컴포넌트
  package-lock.json
  package.json
  src/App.tsx
  src/assets/NavigationBar/add.svg
  src/assets/NavigationBar/home.svg
  src/assets/NavigationBar/profile.svg
  src/assets/NavigationBar/search.svg
  src/assets/NavigationBar/well.svg
  src/assets/header/bell-02.svg
  src/components/common/Header.tsx
  src/components/common/NavigationBar.tsx
  src/components/layout/MainLayout.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/NoticePage.tsx
  src/pages/ReviewAddPage.tsx
  src/pages/SearchPage.tsx
  src/pages/WellPage.tsx
  src/types/custom.d.ts
  tsconfig.json
Labels: feat, 혜나 🤗

#11 [Feat/#6]: color, fontSize 정의, 댓글 바텀시트 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/bottomSheet/Line.svg
  src/components/layout/MainLayout.tsx
  src/hooks/useClickOutside.ts
  src/index.tsx
  src/pages/CommentBottomSheet.tsx
  src/pages/HomePage.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  src/types/styled.d.ts
Labels: feat, 지민 😎

#17 [Feat/#14]: 홈화면 팝업 구현
  public/index.html
  src/App.tsx
  src/assets/popUp/Cancel.svg
  src/components/common/Header.tsx
  src/components/common/NavigationBar.tsx
  src/components/common/popUp/FeedPopUp.tsx
  src/components/layout/MainLayout.tsx
  src/data/dummyData/reportData.ts
  src/pages/CommentBottomSheet.tsx
  src/pages/HomePage.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  src/types/styled.d.ts
Labels: feat, 지민 😎

#20 [Feat / #9]: 홈페이지 구현
  package-lock.json
  package.json
  src/assets/home/comment.svg
  src/assets/home/frologlogo.svg
  src/assets/home/halfstar.svg
  src/assets/home/menu.svg
  src/assets/home/nostar.svg
  src/assets/home/pro_con_tag.svg
  src/assets/home/share.svg
  src/assets/home/star.svg
  src/components/common/home/BookReview.tsx
  src/components/common/home/BookReviewList.tsx
  src/components/common/home/BottomBar.tsx
  src/components/common/home/Content.tsx
  src/components/common/home/ProfileBar.tsx
  src/data/dummyData/homeDummy.ts
  src/pages/HomePage.tsx
  src/styles/GlobalStyles.ts
Labels: feat, 혜나 🤗

#19 [Feat/#18]: 알림 페이지 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/assets/notice/arrow-left.svg
  src/components/common/popUp/FeedPopUp.tsx
  src/components/layout/DefaultLayout.tsx
  src/components/noticePage/AdBanner.tsx
  src/components/noticePage/NoticeItem.tsx
  src/data/dummyData/noticeDummy.ts
  src/data/reportData.ts
  src/pages/NoticePage.tsx
  src/styles/GlobalStyles.ts
Labels: feat, 지민 😎

#21 [Fix]: 오류 수정, 일부 스타일 변경
  src/components/common/Header.tsx
  src/components/common/NavigationBar.tsx
  src/components/home/BookReview.tsx
  src/components/home/BookReviewList.tsx
  src/components/home/BottomBar.tsx
  src/components/home/Content.tsx
  src/components/home/ProfileBar.tsx
  src/pages/HomePage.tsx
Labels: fix

#23 [Setting]: 폰트 세팅 변경
  src/assets/font/font.css
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-100.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-200.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-300.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-500.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-600.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-700.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-800.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-900.ttf
  src/assets/font/ttf/noto-sans-kr-v36-korean_latin-regular.ttf
  src/assets/font/woff/Pretendard-Bold.woff
  src/assets/font/woff/Pretendard-ExtraBold.woff
  src/assets/font/woff/Pretendard-ExtraLight.woff
  src/assets/font/woff/Pretendard-Light.woff
  src/assets/font/woff/Pretendard-Medium.woff
  src/assets/font/woff/Pretendard-Regular.woff
  src/assets/font/woff/Pretendard-SemiBold.woff
  src/assets/font/woff/Pretendard-Thin.woff
  src/assets/font/woff2/Pretendard-Bold.woff2
  src/assets/font/woff2/Pretendard-ExtraBold.woff2
  src/assets/font/woff2/Pretendard-ExtraLight.woff2
  src/assets/font/woff2/Pretendard-Light.woff2
  src/assets/font/woff2/Pretendard-Medium.woff2
  src/assets/font/woff2/Pretendard-Regular.woff2
  src/assets/font/woff2/Pretendard-SemiBold.woff2
  src/assets/font/woff2/Pretendard-Thin.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-100.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-200.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-300.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-500.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-600.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-700.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-800.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-900.woff2
  src/assets/font/woff2/noto-sans-kr-v36-korean_latin-regular.woff2
  src/styles/GlobalStyles.ts
Labels: setting, 지민 😎
